### ISSUE TITLE
SoundConverter has stopped working

### ISSUE THREAD

**Issue by terzag** [flathub/org.soundconverter.SoundConverter#6]
Haven't used SC in a while, so I'm not sure when it stopped working but when I try to run it I get the following errors:
```
Traceback (most recent call last):
  File "/app/bin/soundconverter", line 36, in <module>
    VERSION = pkg_resources.require('soundconverter')[0].version
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'soundconverter' distribution was not found and is required by the application
```
Might be related to an update to the GNOME runtime? I think I got one yesterday or so.

**Comment by jmaibaum** [comment]
Thanks for your report. So far, I have no clue why it's not found, as `soundconverter still builds and installs normally using `flatpak-builder`, yet for some reason, `pkg_resources.require()` (or similar) doesn't find it anymore. I am thus still looking for a proper solution.

In the meantime, I found that setting explicitly setting `PYTHONPATH` to `/app/lib/python3.9/site-packages` makes the application launch again. Does this help for you as well?

```console
flatpak run --env=PYTHONPATH=/app/lib/python3.9/site-packages org.soundconverter.SoundConverter
```

I have no idea why this makes a difference, since `/app/lib/python3.9/site-packages` *is already* in `sys.path`. If it works for you as well though, I might add this as a permanent workaround until someone with more insight into setuptools/pkg_resources can tell me what is going on here.

**Comment by jmaibaum** [comment]
FWIW, I have reported this upstream. Maybe someone from the project developers knows what's going on, see: https://bugs.launchpad.net/soundconverter/+bug/1956623

**Comment by jmaibaum** [comment]
@terzag , if you have time, please check if the test build from #7 (which sets `PYTHONPATH` by default) installs and launches for you?

**Comment by sezanzeb** [comment]
I have installed soundconverter using flatpak, where are the python files that flatpak uses to run soundconverter so that I can try to find a solution?

**Comment by sezanzeb** [comment]
nevermind, found them in `/var/lib/flatpak/app/org.soundconverter.SoundConverter/`

**Comment by terzag** [comment]
When trying the original version with the env option set, it starts but I get the following, not sure if it's normal?
```
ERROR: Disabling mp3-id-tags output. Do you have "gst-plugins-good" installed?
ERROR: Disabling mp3-vbr-tags output. Do you have "gst-plugins-ugly" installed?
soundconverter 4.0.3
```
I don't think I've run SC in flatpak through a terminal before, so the errors about tags might have always been there.

As for the test build, I'm not used much to flatpak: do I have to uninstall the original version (from FlatHub) first or update it with that build?

**Comment by sezanzeb** [comment]
Usually this is available in package managers:

```
➜  ~ pacman -Ss gst-plugins-good
extra/gst-plugins-good 1.18.5-2 [installed]
    Multimedia graph framework - good plugins
```

I don't know how this translates to flatpak

**Comment by terzag** [comment]
I'm on Ubuntu and have the various gstreamer plugins packages installed (base, bad, good, ugly) from the repos but I guess flatpak can't use them, I would assume that SC is looking for them either in the package or from an independent one (or a runtime).

**Comment by jmaibaum** [comment]
@terzag :
> As for the test build, I'm not used much to flatpak: do I have to uninstall the original version (from FlatHub) first or update it with that build?

If you have installed the main version on your system flatpak installation, you can install the test version alongside in your user installation. The command shown by flathubbot is meant for this scenario: The `--user` switch moves it to the user installation.

Given that you were able to launch the app via the `--env` on the commandline means that the test version will likely also work, so you don't have to bother.

**Comment by jmaibaum** [comment]
> When trying the original version with the env option set, it starts but I get the following, not sure if it's normal?
>
> ```ERROR: Disabling mp3-id-tags output. Do you have "gst-plugins-good" installed?
> ERROR: Disabling mp3-vbr-tags output. Do you have "gst-plugins-ugly" installed?
> soundconverter 4.0.3```
It's is unrelated to this issue, and related to how GStreamer plugins are managed within flatpak (which I do not fully wrap my head around to be honest). These errors are present since I started working on the flatpak version of soundconverter and just never got around fixing. I didn't find these errors to cause any trouble though. Exporting to MP3 still works, and I cannot remember losing a single ID3 tag or having trouble playing back VBR MP3 generated by soundconverter. I have to admit though that I don't use MP3 extensively anymore, so it might still cause issues. I was always planning to look into this more seriously if somebody came up with an example file/configuration that does not work. So if you find something not working correctly, please file an issue.
